---
title: "Bayesian Model Averaging with the Laplace Approximation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Bayesian Model Averaging with the Laplace Approximation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(BayesianId)
```

```{r load_data}
data("penguins")
head(penguins)
```

```{r full_model}
mass_breg_full = breg_laplace(body_mass ~ island*sex + flipper_len,
                              data = na.omit(penguins),
                              prior_scale = 0.707)
mass_breg_full$log_evidence
```

```{r check_full_model}
plot(mass_breg_full, xvar = "flipper_len")
```

```{r create_bma_object}
tic = Sys.time()
mass_breg_bma = bma(mass_breg_full)
toc = Sys.time()
print(toc - tic)
```

```{r print}
print(mass_breg_bma)
```

```{r, contrast}
contrast(mass_breg_bma, factors = c("island", "sex"), ref = "Biscoe male")
```

```{r term_probs}
summary(mass_breg_bma, type = "term_probs")
```

```{r term_odds}
summary(mass_breg_bma, type = "term_odds")
```

```{r model_probs}
summary(mass_breg_bma, type = "model_probs")
```

```{r model_odds}
summary(mass_breg_bma, type = "model_odds")
```

```{r est}
summary(mass_breg_bma, type = "est")
```
