// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4bernoulli_logistic_est_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bernoulli_logistic_intercept_est_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bernoulli_logistic_intercept_sim_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bernoulli_logistic_sim_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4binomial_logistic_est_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4binomial_logistic_intercept_est_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4binomial_logistic_intercept_sim_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4binomial_logistic_sim_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lognormal_linear_est_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lognormal_linear_intercept_est_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lognormal_linear_intercept_sim_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lognormal_linear_sim_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4normal_linear_est_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4normal_linear_intercept_est_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4normal_linear_intercept_sim_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4normal_linear_sim_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4poisson_est_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4poisson_intercept_est_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4poisson_intercept_sim_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4poisson_sim_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4right_censored_linear_est_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4right_censored_linear_intercept_est_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4right_censored_linear_intercept_sim_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4right_censored_linear_sim_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4bernoulli_logistic_est_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bernoulli_logistic_est_mod, 0},
    {"_rcpp_module_boot_stan_fit4bernoulli_logistic_intercept_est_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bernoulli_logistic_intercept_est_mod, 0},
    {"_rcpp_module_boot_stan_fit4bernoulli_logistic_intercept_sim_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bernoulli_logistic_intercept_sim_mod, 0},
    {"_rcpp_module_boot_stan_fit4bernoulli_logistic_sim_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bernoulli_logistic_sim_mod, 0},
    {"_rcpp_module_boot_stan_fit4binomial_logistic_est_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4binomial_logistic_est_mod, 0},
    {"_rcpp_module_boot_stan_fit4binomial_logistic_intercept_est_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4binomial_logistic_intercept_est_mod, 0},
    {"_rcpp_module_boot_stan_fit4binomial_logistic_intercept_sim_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4binomial_logistic_intercept_sim_mod, 0},
    {"_rcpp_module_boot_stan_fit4binomial_logistic_sim_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4binomial_logistic_sim_mod, 0},
    {"_rcpp_module_boot_stan_fit4lognormal_linear_est_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lognormal_linear_est_mod, 0},
    {"_rcpp_module_boot_stan_fit4lognormal_linear_intercept_est_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lognormal_linear_intercept_est_mod, 0},
    {"_rcpp_module_boot_stan_fit4lognormal_linear_intercept_sim_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lognormal_linear_intercept_sim_mod, 0},
    {"_rcpp_module_boot_stan_fit4lognormal_linear_sim_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lognormal_linear_sim_mod, 0},
    {"_rcpp_module_boot_stan_fit4normal_linear_est_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4normal_linear_est_mod, 0},
    {"_rcpp_module_boot_stan_fit4normal_linear_intercept_est_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4normal_linear_intercept_est_mod, 0},
    {"_rcpp_module_boot_stan_fit4normal_linear_intercept_sim_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4normal_linear_intercept_sim_mod, 0},
    {"_rcpp_module_boot_stan_fit4normal_linear_sim_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4normal_linear_sim_mod, 0},
    {"_rcpp_module_boot_stan_fit4poisson_est_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4poisson_est_mod, 0},
    {"_rcpp_module_boot_stan_fit4poisson_intercept_est_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4poisson_intercept_est_mod, 0},
    {"_rcpp_module_boot_stan_fit4poisson_intercept_sim_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4poisson_intercept_sim_mod, 0},
    {"_rcpp_module_boot_stan_fit4poisson_sim_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4poisson_sim_mod, 0},
    {"_rcpp_module_boot_stan_fit4right_censored_linear_est_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4right_censored_linear_est_mod, 0},
    {"_rcpp_module_boot_stan_fit4right_censored_linear_intercept_est_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4right_censored_linear_intercept_est_mod, 0},
    {"_rcpp_module_boot_stan_fit4right_censored_linear_intercept_sim_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4right_censored_linear_intercept_sim_mod, 0},
    {"_rcpp_module_boot_stan_fit4right_censored_linear_sim_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4right_censored_linear_sim_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesianId(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
