# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("bernoulli_logistic_est", "bernoulli_logistic_intercept_est", "bernoulli_logistic_intercept_sim", "bernoulli_logistic_sim", "lognormal_linear_est", "lognormal_linear_intercept_est", "lognormal_linear_intercept_sim", "lognormal_linear_sim", "normal_linear_est", "normal_linear_intercept_est", "normal_linear_intercept_sim", "normal_linear_sim", "poisson_est", "poisson_intercept_est", "poisson_intercept_sim", "poisson_sim", "right_censored_linear_est", "right_censored_linear_intercept_est", "right_censored_linear_intercept_sim", "right_censored_linear_sim")

# load each stan module
Rcpp::loadModule("stan_fit4bernoulli_logistic_est_mod", what = TRUE)
Rcpp::loadModule("stan_fit4bernoulli_logistic_intercept_est_mod", what = TRUE)
Rcpp::loadModule("stan_fit4bernoulli_logistic_intercept_sim_mod", what = TRUE)
Rcpp::loadModule("stan_fit4bernoulli_logistic_sim_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lognormal_linear_est_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lognormal_linear_intercept_est_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lognormal_linear_intercept_sim_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lognormal_linear_sim_mod", what = TRUE)
Rcpp::loadModule("stan_fit4normal_linear_est_mod", what = TRUE)
Rcpp::loadModule("stan_fit4normal_linear_intercept_est_mod", what = TRUE)
Rcpp::loadModule("stan_fit4normal_linear_intercept_sim_mod", what = TRUE)
Rcpp::loadModule("stan_fit4normal_linear_sim_mod", what = TRUE)
Rcpp::loadModule("stan_fit4poisson_est_mod", what = TRUE)
Rcpp::loadModule("stan_fit4poisson_intercept_est_mod", what = TRUE)
Rcpp::loadModule("stan_fit4poisson_intercept_sim_mod", what = TRUE)
Rcpp::loadModule("stan_fit4poisson_sim_mod", what = TRUE)
Rcpp::loadModule("stan_fit4right_censored_linear_est_mod", what = TRUE)
Rcpp::loadModule("stan_fit4right_censored_linear_intercept_est_mod", what = TRUE)
Rcpp::loadModule("stan_fit4right_censored_linear_intercept_sim_mod", what = TRUE)
Rcpp::loadModule("stan_fit4right_censored_linear_sim_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
})
